adds getRandomNumber and getStringLength functions
htmlacademy-javascript/1281335-kekstagram-simple-27 pull request #2
Opened 2022-11-05 18:48 UTC by KKseniya

2022-11-06 20:03 UTC, o-bender requested changes

2022-11-06 20:03 UTC, o-bender commented on index.html
> +    <script src="/js/main.js"></script>
Секцию script перенеси в конец body.

2022-11-06 20:03 UTC, o-bender commented on .eslintrc
> +rules:
Эта секция откуда и зачем взялась?)

2022-11-06 20:03 UTC, o-bender commented on index.html
> +  <head>
Наверное нет смысла спрашивать почему html разметка переформатирована? Проблемы в этом нет, но просто интересно)

2022-11-06 20:03 UTC, o-bender commented on js/main.js
> +function getRandomNumber(min, max) {
Сейчас вообще всё равно, т.к. эти две функции в будущем надо будет удалить. Но дальше пользуйся стрелочными функциями.

2022-11-06 20:03 UTC, o-bender commented on js/main.js
> +  if (
Такие условия лучше писать так:
```
const isInvalidValues = typeof min !== 'number' ||
    typeof max !== 'number' ||
    min < 0 ||
    max < 0 ||
    min === max ||
    min > max;
if (isInvalidValues) {
     return NaN;
}
```

2022-11-06 20:03 UTC, o-bender commented on js/main.js
> +  if (
Лично я скептически отношусь к таким проверкам в js: `typeof min !== 'number'`. Это попытка сделать его строго типизированным. И если в каждой функции в которую должны приходить цифры делать такие проверки... Твой код превратится в однотипное, сложно читаемое нечто.
Так что я бы написал так:
```
if (min >= 0  && max >= 0) {
    if (min > max) {
        [min, max] = [max, min];
    }
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min + 1)) + min;
}
```
Почему:
1. 'some string' < 0 результат false, 'some string' > 0 результат тоже false. Это ещё и к вопросу почему не стоит везде использовать такие проверки `typeof max !== 'number'`.
2. Если min и max равны, ну значит результирующий набор из одного значения. Граничный случай, но вполне допустимый.
3. Если min и max перепутаны, то можно просто их махнуть местами :), но можно и оставить как было, т.е. сказать разработчику, что он неправ.

2022-11-06 21:16 UTC, KKseniya commented on .eslintrc
> +rules:
vs code автоматически исправлял на двойные кавычки
Указание default formatted как eslint не помогало
Пришлось прописать правило, чтобы vs code мог правильно импортировать правила для автоматического исправления)

2022-11-06 21:20 UTC, KKseniya commented on index.html
> +  <head>
При сохранении происходит автоформатирование кода по eslint. Если так не нужно делать, отключу его)

2022-11-06 22:01 UTC, KKseniya commented on index.html
> +    <script src="/js/main.js"></script>
Готово - https://skr.sh/sGmjBa34HpE

2022-11-06 22:02 UTC, KKseniya commented on js/main.js
> +function getRandomNumber(min, max) {
Исправила - https://skr.sh/sGmaXtmI3dQ

2022-11-06 22:03 UTC, KKseniya commented on js/main.js
> +  if (
1. Поняла, учту, спасибо)
2. Сначала учла именно так случай равенства min и max, но потом решила оставить такой вариант ошибочным
3. Сделано - https://skr.sh/sGmzkmg7YKA

2022-11-07 07:51 UTC, o-bender commented
Только вот это убери: `no-console: "off"`. А то консоль логи это критерий.

2022-11-07 07:51 UTC, merged